name: Compile server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Install bam
        run: sudo apt install bam=0.4.0-5

      - name: Compile binary server file
        run: bam server_release

      - name: Test running
        run: |
            ./xPanic-Server exec autoexec_server.cfg.example;sv_name GitHub Test xPanic Server;
